//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoYoStudio.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YoYoStudio.Resource.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账号格式错误.
        /// </summary>
        public static string AccountFormatWrong {
            get {
                return ResourceManager.GetString("AccountFormatWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账号，密码不能为空.
        /// </summary>
        public static string AccountPasswordCannotBeNull {
            get {
                return ResourceManager.GetString("AccountPasswordCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您已经进入了房间，确定要离开房间重新进入新房间吗？.
        /// </summary>
        public static string AlreadyInRoom {
            get {
                return ResourceManager.GetString("AlreadyInRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}不能为空.
        /// </summary>
        public static string CannotBeEmpty {
            get {
                return ResourceManager.GetString("CannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择用户没有接受礼物权限.
        /// </summary>
        public static string CannotReceiveGift {
            get {
                return ResourceManager.GetString("CannotReceiveGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您没有发送礼物权限.
        /// </summary>
        public static string CannotSendGift {
            get {
                return ResourceManager.GetString("CannotSendGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在连接服务器，请稍后 ....
        /// </summary>
        public static string ConnectingToServer {
            get {
                return ResourceManager.GetString("ConnectingToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 进入房间失败，请稍后重试或者联系管理员.
        /// </summary>
        public static string EnterRoomFailed {
            get {
                return ResourceManager.GetString("EnterRoomFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出错，请稍后再试或者联系管理员。.
        /// </summary>
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无效用户，请重新登陆.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您被{0}踢出房间.
        /// </summary>
        public static string KickOut {
            get {
                return ResourceManager.GetString("KickOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 玩儿命加载中... ....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录失败.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大只能上传{0}K的文件.
        /// </summary>
        public static string MaxFileUpload {
            get {
                return ResourceManager.GetString("MaxFileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歌曲正在播放中，确定要停止播放吗？.
        /// </summary>
        public static string MusicPlaying {
            get {
                return ResourceManager.GetString("MusicPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必须.
        /// </summary>
        public static string MustAgreeRegister {
            get {
                return ResourceManager.GetString("MustAgreeRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有权限执行该操作.
        /// </summary>
        public static string NoPrivilege {
            get {
                return ResourceManager.GetString("NoPrivilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前没有分配注册号码，请联系管理员.
        /// </summary>
        public static string NoRegisterUserIdAvailable {
            get {
                return ResourceManager.GetString("NoRegisterUserIdAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有足够的钱币执行此操作，请先充值。.
        /// </summary>
        public static string NotEnoughMoney {
            get {
                return ResourceManager.GetString("NotEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码不一致.
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册失败，请稍后再试.
        /// </summary>
        public static string RegisterFailed {
            get {
                return ResourceManager.GetString("RegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册成功！您的账号是：{0}.
        /// </summary>
        public static string RegisterSucceeded {
            get {
                return ResourceManager.GetString("RegisterSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存失败.
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存成功.
        /// </summary>
        public static string SaveSucceeded {
            get {
                return ResourceManager.GetString("SaveSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知错误.
        /// </summary>
        public static string UnkownError {
            get {
                return ResourceManager.GetString("UnkownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传错误.
        /// </summary>
        public static string UploadError {
            get {
                return ResourceManager.GetString("UploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传成功.
        /// </summary>
        public static string UploadSucceed {
            get {
                return ResourceManager.GetString("UploadSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法登陆，{0}被封，请联系系统管理员.
        /// </summary>
        public static string UserBlocked {
            get {
                return ResourceManager.GetString("UserBlocked", resourceCulture);
            }
        }
    }
}
