//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoYoStudio.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YoYoStudio.Resource.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9258多人视频聊天室.
        /// </summary>
        public static string _9258ChatApplication {
            get {
                return ResourceManager.GetString("_9258ChatApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请记住此号码以便注册成功后登录时使用.
        /// </summary>
        public static string AccountIdDescription {
            get {
                return ResourceManager.GetString("AccountIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户ID.
        /// </summary>
        public static string AccountIdLabel {
            get {
                return ResourceManager.GetString("AccountIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字母或者数字的组合.
        /// </summary>
        public static string AccountNameDescription {
            get {
                return ResourceManager.GetString("AccountNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户昵称.
        /// </summary>
        public static string AccountNameLabel {
            get {
                return ResourceManager.GetString("AccountNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统管理员.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年龄.
        /// </summary>
        public static string AgeLabel {
            get {
                return ResourceManager.GetString("AgeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 官方代理.
        /// </summary>
        public static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 代理充值.
        /// </summary>
        public static string AgentDeposit {
            get {
                return ResourceManager.GetString("AgentDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入代理号码.
        /// </summary>
        public static string AgentIdRequired {
            get {
                return ResourceManager.GetString("AgentIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有应用程序.
        /// </summary>
        public static string AllApplication {
            get {
                return ResourceManager.GetString("AllApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有权限.
        /// </summary>
        public static string AllCommand {
            get {
                return ResourceManager.GetString("AllCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有图片.
        /// </summary>
        public static string AllImage {
            get {
                return ResourceManager.GetString("AllImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 为代理分配用户号码.
        /// </summary>
        public static string AllocatAgentUserId {
            get {
                return ResourceManager.GetString("AllocatAgentUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有用户级别.
        /// </summary>
        public static string AllRole {
            get {
                return ResourceManager.GetString("AllRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用程序图标.
        /// </summary>
        public static string ApplicationImage {
            get {
                return ResourceManager.GetString("ApplicationImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用程序列表.
        /// </summary>
        public static string ApplicationList {
            get {
                return ResourceManager.GetString("ApplicationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音频设置.
        /// </summary>
        public static string AudioConfiguration {
            get {
                return ResourceManager.GetString("AudioConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动登录.
        /// </summary>
        public static string AutoLoginLabel {
            get {
                return ResourceManager.GetString("AutoLoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 后台程序.
        /// </summary>
        public static string BackendApplication {
            get {
                return ResourceManager.GetString("BackendApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 黑名单.
        /// </summary>
        public static string BlackList {
            get {
                return ResourceManager.GetString("BlackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁封管理.
        /// </summary>
        public static string BlockCommand {
            get {
                return ResourceManager.GetString("BlockCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁封IP.
        /// </summary>
        public static string BlockIP {
            get {
                return ResourceManager.GetString("BlockIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁封Mac.
        /// </summary>
        public static string BlockMac {
            get {
                return ResourceManager.GetString("BlockMac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁封类型管理.
        /// </summary>
        public static string BlockTypeCommand {
            get {
                return ResourceManager.GetString("BlockTypeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁封用户.
        /// </summary>
        public static string BlockUser {
            get {
                return ResourceManager.GetString("BlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览.
        /// </summary>
        public static string BrowserLabel {
            get {
                return ResourceManager.GetString("BrowserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自拍头像.
        /// </summary>
        public static string CameraPhoto {
            get {
                return ResourceManager.GetString("CameraPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拍照.
        /// </summary>
        public static string CapturePhoto {
            get {
                return ResourceManager.GetString("CapturePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更换头像.
        /// </summary>
        public static string ChangePhotoLabel {
            get {
                return ResourceManager.GetString("ChangePhotoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9258 大厅服务.
        /// </summary>
        public static string ChatService {
            get {
                return ResourceManager.GetString("ChatService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已确认，关闭.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限图标.
        /// </summary>
        public static string CommandImage {
            get {
                return ResourceManager.GetString("CommandImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成注册.
        /// </summary>
        public static string CompleteRegister {
            get {
                return ResourceManager.GetString("CompleteRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认密码.
        /// </summary>
        public static string ConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9258 后台管理系统.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义.
        /// </summary>
        public static string CustomizedMotion {
            get {
                return ResourceManager.GetString("CustomizedMotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认权限.
        /// </summary>
        public static string DefaultCommand {
            get {
                return ResourceManager.GetString("DefaultCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认礼物组.
        /// </summary>
        public static string DefaultGiftGroup {
            get {
                return ResourceManager.GetString("DefaultGiftGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认用户级别.
        /// </summary>
        public static string DefaultRole {
            get {
                return ResourceManager.GetString("DefaultRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认房间组.
        /// </summary>
        public static string DefaultRoomGroup {
            get {
                return ResourceManager.GetString("DefaultRoomGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用程序管理.
        /// </summary>
        public static string DefineApplication {
            get {
                return ResourceManager.GetString("DefineApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 后台权限管理.
        /// </summary>
        public static string DefineBackendCommand {
            get {
                return ResourceManager.GetString("DefineBackendCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限管理.
        /// </summary>
        public static string DefineCommand {
            get {
                return ResourceManager.GetString("DefineCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 汇率管理.
        /// </summary>
        public static string DefineExchangeRate {
            get {
                return ResourceManager.GetString("DefineExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前台权限管理.
        /// </summary>
        public static string DefineFrontendCommand {
            get {
                return ResourceManager.GetString("DefineFrontendCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 礼物管理.
        /// </summary>
        public static string DefineGift {
            get {
                return ResourceManager.GetString("DefineGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 礼物组管理.
        /// </summary>
        public static string DefineGiftGroup {
            get {
                return ResourceManager.GetString("DefineGiftGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户充值.
        /// </summary>
        public static string DefineMoney {
            get {
                return ResourceManager.GetString("DefineMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户级别管理.
        /// </summary>
        public static string DefineRole {
            get {
                return ResourceManager.GetString("DefineRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户级别权限管理.
        /// </summary>
        public static string DefineRoleCommand {
            get {
                return ResourceManager.GetString("DefineRoleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 房间管理.
        /// </summary>
        public static string DefineRoom {
            get {
                return ResourceManager.GetString("DefineRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 房间组管理.
        /// </summary>
        public static string DefineRoomGroup {
            get {
                return ResourceManager.GetString("DefineRoomGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户管理.
        /// </summary>
        public static string DefineUser {
            get {
                return ResourceManager.GetString("DefineUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户权限管理.
        /// </summary>
        public static string DefineUserCommand {
            get {
                return ResourceManager.GetString("DefineUserCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除所有.
        /// </summary>
        public static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除选中的图片.
        /// </summary>
        public static string DeleteSelectedImage {
            get {
                return ResourceManager.GetString("DeleteSelectedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除选中分组.
        /// </summary>
        public static string DeleteSelectedImageGroup {
            get {
                return ResourceManager.GetString("DeleteSelectedImageGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除选中歌曲.
        /// </summary>
        public static string DeleteSelectedMusic {
            get {
                return ResourceManager.GetString("DeleteSelectedMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下麦.
        /// </summary>
        public static string DownMicLabel {
            get {
                return ResourceManager.GetString("DownMicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 兑换.
        /// </summary>
        public static string Exchange {
            get {
                return ResourceManager.GetString("Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 女.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最近修改时间.
        /// </summary>
        public static string FileLastModifiedLabel {
            get {
                return ResourceManager.GetString("FileLastModifiedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件大小.
        /// </summary>
        public static string FileSizeLabel {
            get {
                return ResourceManager.GetString("FileSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 功能列表.
        /// </summary>
        public static string FunctionList {
            get {
                return ResourceManager.GetString("FunctionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性别.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生成图片包.
        /// </summary>
        public static string GenerateImagePack {
            get {
                return ResourceManager.GetString("GenerateImagePack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 礼物分组图片.
        /// </summary>
        public static string GiftGroupImage {
            get {
                return ResourceManager.GetString("GiftGroupImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 礼物图片.
        /// </summary>
        public static string GiftImage {
            get {
                return ResourceManager.GetString("GiftImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 礼物接受和赠送查询.
        /// </summary>
        public static string GiftInOutHistoryInquiry {
            get {
                return ResourceManager.GetString("GiftInOutHistoryInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 头像图片.
        /// </summary>
        public static string HeaderImage {
            get {
                return ResourceManager.GetString("HeaderImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片不存在.
        /// </summary>
        public static string ImageNotAvailable {
            get {
                return ResourceManager.GetString("ImageNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入gif.
        /// </summary>
        public static string ImportGif {
            get {
                return ResourceManager.GetString("ImportGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80*80.
        /// </summary>
        public static string LargeScale {
            get {
                return ResourceManager.GetString("LargeScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上次登录.
        /// </summary>
        public static string LastLoginTimeLabel {
            get {
                return ResourceManager.GetString("LastLoginTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载歌曲，请稍后....
        /// </summary>
        public static string LoadingMusic {
            get {
                return ResourceManager.GetString("LoadingMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本地照片.
        /// </summary>
        public static string LocalPhoto {
            get {
                return ResourceManager.GetString("LocalPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注销.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 男.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理菜单.
        /// </summary>
        public static string ManagementMenu {
            get {
                return ResourceManager.GetString("ManagementMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理工具.
        /// </summary>
        public static string ManagementTool {
            get {
                return ResourceManager.GetString("ManagementTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}至少{2}位.
        /// </summary>
        public static string MinimalLength {
            get {
                return ResourceManager.GetString("MinimalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 镜像.
        /// </summary>
        public static string MirrorLabel {
            get {
                return ResourceManager.GetString("MirrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音乐.
        /// </summary>
        public static string MusicLabel {
            get {
                return ResourceManager.GetString("MusicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歌曲管理.
        /// </summary>
        public static string MusicManagement {
            get {
                return ResourceManager.GetString("MusicManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  歌曲名称.
        /// </summary>
        public static string MusicNameLabel {
            get {
                return ResourceManager.GetString("MusicNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建分组.
        /// </summary>
        public static string NewGroup {
            get {
                return ResourceManager.GetString("NewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新密码.
        /// </summary>
        public static string NewPasswordLabel {
            get {
                return ResourceManager.GetString("NewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昵称.
        /// </summary>
        public static string NickNameLabel {
            get {
                return ResourceManager.GetString("NickNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未提交.
        /// </summary>
        public static string NotSubmitted {
            get {
                return ResourceManager.GetString("NotSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旧密码.
        /// </summary>
        public static string OldPasswordLabel {
            get {
                return ResourceManager.GetString("OldPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上麦.
        /// </summary>
        public static string OnMicLabel {
            get {
                return ResourceManager.GetString("OnMicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码答案.
        /// </summary>
        public static string PasswordAnswerLabel {
            get {
                return ResourceManager.GetString("PasswordAnswerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码管理.
        /// </summary>
        public static string PasswordCommand {
            get {
                return ResourceManager.GetString("PasswordCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码不能为空.
        /// </summary>
        public static string PasswordDescription {
            get {
                return ResourceManager.GetString("PasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码格式错误，保存失败！.
        /// </summary>
        public static string PasswordInvalid {
            get {
                return ResourceManager.GetString("PasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入密码.
        /// </summary>
        public static string PasswordIsRequired {
            get {
                return ResourceManager.GetString("PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码长度必须是6~10位。.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 两次输入密码不一致.
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码问题.
        /// </summary>
        public static string PasswordQuestionLabel {
            get {
                return ResourceManager.GetString("PasswordQuestionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 至少需要一个大写字母。.
        /// </summary>
        public static string PasswordRequireCapital {
            get {
                return ResourceManager.GetString("PasswordRequireCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资产.
        /// </summary>
        public static string PersonalAssets {
            get {
                return ResourceManager.GetString("PersonalAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 座驾.
        /// </summary>
        public static string PersonalCars {
            get {
                return ResourceManager.GetString("PersonalCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基本信息.
        /// </summary>
        public static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人信息管理.
        /// </summary>
        public static string PersonalInfoCommand {
            get {
                return ResourceManager.GetString("PersonalInfoCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人详细信息.
        /// </summary>
        public static string PersonalInfoConfiguration {
            get {
                return ResourceManager.GetString("PersonalInfoConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人管理.
        /// </summary>
        public static string PersonalManagement {
            get {
                return ResourceManager.GetString("PersonalManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 房间.
        /// </summary>
        public static string PersonalRooms {
            get {
                return ResourceManager.GetString("PersonalRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 微博.
        /// </summary>
        public static string PersonalWebo {
            get {
                return ResourceManager.GetString("PersonalWebo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. 可以使用鼠标左键拖动圈定图片区域.
        /// </summary>
        public static string PhotoRule1 {
            get {
                return ResourceManager.GetString("PhotoRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. 禁止使用色情、反动、暴力等非法内容的图片.
        /// </summary>
        public static string PhotoRule2 {
            get {
                return ResourceManager.GetString("PhotoRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图像文件 (*.bmp, *.jpg, *.png)|*.bmp;*.jpg;*.png.
        /// </summary>
        public static string PhotoType {
            get {
                return ResourceManager.GetString("PhotoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 播放.
        /// </summary>
        public static string PlayMusicLabel {
            get {
                return ResourceManager.GetString("PlayMusicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预览.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 私麦.
        /// </summary>
        public static string PrivateMicLabel {
            get {
                return ResourceManager.GetString("PrivateMicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已处理，请确认.
        /// </summary>
        public static string Processed {
            get {
                return ResourceManager.GetString("Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string Prompt {
            get {
                return ResourceManager.GetString("Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只读.
        /// </summary>
        public static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只读权限.
        /// </summary>
        public static string ReadOnlyCommand {
            get {
                return ResourceManager.GetString("ReadOnlyCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只读用户.
        /// </summary>
        public static string ReadOnlyUser {
            get {
                return ResourceManager.GetString("ReadOnlyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 房间管理.
        /// </summary>
        public static string RecommendRoom {
            get {
                return ResourceManager.GetString("RecommendRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        public static string RefreshLabel {
            get {
                return ResourceManager.GetString("RefreshLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同意注册协议.
        /// </summary>
        public static string RegisterAgreement {
            get {
                return ResourceManager.GetString("RegisterAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册用户.
        /// </summary>
        public static string RegisterUser {
            get {
                return ResourceManager.GetString("RegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收藏.
        /// </summary>
        public static string ReserveRoom {
            get {
                return ResourceManager.GetString("ReserveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户级别图标.
        /// </summary>
        public static string RoleImage {
            get {
                return ResourceManager.GetString("RoleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 房间管理员.
        /// </summary>
        public static string RoomAdministrator {
            get {
                return ResourceManager.GetString("RoomAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 室长.
        /// </summary>
        public static string RoomDirectory {
            get {
                return ResourceManager.GetString("RoomDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 房间组图片.
        /// </summary>
        public static string RoomGroupImage {
            get {
                return ResourceManager.GetString("RoomGroupImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 房间图片.
        /// </summary>
        public static string RoomImage {
            get {
                return ResourceManager.GetString("RoomImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 房间收入查询.
        /// </summary>
        public static string RoomIncomeHistoryInquiry {
            get {
                return ResourceManager.GetString("RoomIncomeHistoryInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9258房价服务.
        /// </summary>
        public static string RoomService {
            get {
                return ResourceManager.GetString("RoomService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 积分充值.
        /// </summary>
        public static string ScoreDeposit {
            get {
                return ResourceManager.GetString("ScoreDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 积分兑换金币.
        /// </summary>
        public static string ScoreToMoney {
            get {
                return ResourceManager.GetString("ScoreToMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秘麦.
        /// </summary>
        public static string SecretMicLabel {
            get {
                return ResourceManager.GetString("SecretMicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安全设置.
        /// </summary>
        public static string SecurityConfiguration {
            get {
                return ResourceManager.GetString("SecurityConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结算管理.
        /// </summary>
        public static string SettlementManagement {
            get {
                return ResourceManager.GetString("SettlementManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40*40.
        /// </summary>
        public static string SmallScale {
            get {
                return ResourceManager.GetString("SmallScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 聊天表情图片.
        /// </summary>
        public static string SmileImage {
            get {
                return ResourceManager.GetString("SmileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表情管理.
        /// </summary>
        public static string SmileManagement {
            get {
                return ResourceManager.GetString("SmileManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 印章图片.
        /// </summary>
        public static string StampImage {
            get {
                return ResourceManager.GetString("StampImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 印章管理.
        /// </summary>
        public static string StampManagement {
            get {
                return ResourceManager.GetString("StampManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 屏幕截图.
        /// </summary>
        public static string StartCaptureScreen {
            get {
                return ResourceManager.GetString("StartCaptureScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止.
        /// </summary>
        public static string StopMusicLabel {
            get {
                return ResourceManager.GetString("StopMusicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已提交，等待处理.
        /// </summary>
        public static string Submitted {
            get {
                return ResourceManager.GetString("Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要切换到其他用户吗？.
        /// </summary>
        public static string SwitchUserConfirm {
            get {
                return ResourceManager.GetString("SwitchUserConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 后台管理系统.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 立即体验.
        /// </summary>
        public static string TryNow {
            get {
                return ResourceManager.GetString("TryNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传.
        /// </summary>
        public static string UploadMusicLabel {
            get {
                return ResourceManager.GetString("UploadMusicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户充值.
        /// </summary>
        public static string UserDeposit {
            get {
                return ResourceManager.GetString("UserDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 充值记录查询.
        /// </summary>
        public static string UserDepositHistoryInquiry {
            get {
                return ResourceManager.GetString("UserDepositHistoryInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 兑换记录查询.
        /// </summary>
        public static string UserExchangeHisotryInquiry {
            get {
                return ResourceManager.GetString("UserExchangeHisotryInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户号码管理.
        /// </summary>
        public static string UserIdManagement {
            get {
                return ResourceManager.GetString("UserIdManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入用户名.
        /// </summary>
        public static string UserNameIsRequired {
            get {
                return ResourceManager.GetString("UserNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 升降级.
        /// </summary>
        public static string UserRoleUpDown {
            get {
                return ResourceManager.GetString("UserRoleUpDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 视频设置.
        /// </summary>
        public static string VideoConfiguration {
            get {
                return ResourceManager.GetString("VideoConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 视频质量调节.
        /// </summary>
        public static string VideoQualityLabel {
            get {
                return ResourceManager.GetString("VideoQualityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9258媒体频道欢迎您.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
